// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple.proto

package simple

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SimpleMessage_MsgMode int32

const (
	SimpleMessage_MESSAGE SimpleMessage_MsgMode = 0
	SimpleMessage_FILE    SimpleMessage_MsgMode = 1
	SimpleMessage_KEY     SimpleMessage_MsgMode = 2
)

var SimpleMessage_MsgMode_name = map[int32]string{
	0: "MESSAGE",
	1: "FILE",
	2: "KEY",
}
var SimpleMessage_MsgMode_value = map[string]int32{
	"MESSAGE": 0,
	"FILE":    1,
	"KEY":     2,
}

func (x SimpleMessage_MsgMode) String() string {
	return proto.EnumName(SimpleMessage_MsgMode_name, int32(x))
}
func (SimpleMessage_MsgMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_simple_e0778bb3c7298d9a, []int{0, 0}
}

// [START messages]
type SimpleMessage struct {
	Mode                 SimpleMessage_MsgMode `protobuf:"varint,1,opt,name=mode,enum=simple.SimpleMessage_MsgMode" json:"mode,omitempty"`
	Data                 []byte                `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SimpleMessage) Reset()         { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()    {}
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_simple_e0778bb3c7298d9a, []int{0}
}
func (m *SimpleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMessage.Unmarshal(m, b)
}
func (m *SimpleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMessage.Marshal(b, m, deterministic)
}
func (dst *SimpleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMessage.Merge(dst, src)
}
func (m *SimpleMessage) XXX_Size() int {
	return xxx_messageInfo_SimpleMessage.Size(m)
}
func (m *SimpleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMessage proto.InternalMessageInfo

func (m *SimpleMessage) GetMode() SimpleMessage_MsgMode {
	if m != nil {
		return m.Mode
	}
	return SimpleMessage_MESSAGE
}

func (m *SimpleMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleMessage)(nil), "simple.SimpleMessage")
	proto.RegisterEnum("simple.SimpleMessage_MsgMode", SimpleMessage_MsgMode_name, SimpleMessage_MsgMode_value)
}

func init() { proto.RegisterFile("simple.proto", fileDescriptor_simple_e0778bb3c7298d9a) }

var fileDescriptor_simple_e0778bb3c7298d9a = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xce, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x1a, 0x19, 0xb9,
	0x78, 0x83, 0xc1, 0x4c, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21, 0x43, 0x2e, 0x96, 0xdc,
	0xfc, 0x94, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x59, 0x3d, 0xa8, 0x36, 0x14, 0x45,
	0x7a, 0xbe, 0xc5, 0xe9, 0xbe, 0xf9, 0x29, 0xa9, 0x41, 0x60, 0xa5, 0x42, 0x42, 0x5c, 0x2c, 0x29,
	0x89, 0x25, 0x89, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x92, 0x26, 0x17, 0x3b,
	0x54, 0x91, 0x10, 0x37, 0x17, 0xbb, 0xaf, 0x6b, 0x70, 0xb0, 0xa3, 0xbb, 0xab, 0x00, 0x83, 0x10,
	0x07, 0x17, 0x8b, 0x9b, 0xa7, 0x8f, 0xab, 0x00, 0xa3, 0x10, 0x3b, 0x17, 0xb3, 0xb7, 0x6b, 0xa4,
	0x00, 0x53, 0x12, 0x1b, 0xd8, 0x49, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xe5, 0x2b,
	0xe3, 0xa2, 0x00, 0x00, 0x00,
}
